menu:
    Blog: /
    Archive: /archives/
    Category: /categories/
    Messages: /messages/
    # GitHub: https://github.com/stdwal
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: stdwal
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2017
